### ISSUE TITLE
一起研究占星星盘如何你的联系方式是多少

### ISSUE THREAD

**Issue by mienv567** [nastal/swe_calc#1]
我的联系方式QQ 158117261

**Comment by mienv567** [comment]
?

**Comment by nastal** [comment]
Sorry, could you use English, please?

**Comment by mienv567** [comment]
I like astrology. Recently, I want to develop a star disk, which can be combined and transported. Do you have any interest in this field? Similar to Iphone AppStore Astro chart or time nomad

**Comment by nastal** [comment]
Hi,
yes I'm interested in some vedic astrology approaches.

2018-06-07 3:52 GMT+03:00 mienv567 <notifications@github.com>:
